<!DOCTYPE html>
<!-- Header //-->
<html>

<head>

    <title>Phire Stats : <?=$title; ?></title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="none" />
    <meta name="viewport" content="initial-scale=1.0">

    <link type="text/css" rel="stylesheet" href="//fonts.googleapis.com/css?family=Source+Sans+Pro:400,400italic,700,700italic" />
    <link rel="stylesheet" type="text/css" href="/css/styles.css" />
    <link rel="shortcut icon" href="/img/phire-icon.png" type="image/png" />

</head>

<body>
<a name="top"></a>
<div id="content">
