<?php include __DIR__ . '/inc/header.phtml'; ?>
<?php include __DIR__ . '/inc/nav.phtml'; ?>
<!-- Content //-->
    <a style="float: right;" href="#averages">Averages</a>
    <h1 class="header-top-border">Phire Stats : <?=$title; ?></h1>
<?php if (isset($stats) && (count($stats) > 0)): ?>
<?php if (isset($pages) && (null !== $pages)): ?>
    <div class="page-links"><?=$pages; ?></div>
<?php endif; ?>
<?php
if (isset($_GET['modules'])):
    $resource = '&modules=1';
elseif (isset($_GET['themes'])):
    $resource = '&themes=1';
else:
    $resource = null;
endif; ?>
    <table class="data-table" cellpadding="0" cellspacing="0">
        <tr>
            <th><a href="/?sort=id<?=$resource; ?>">#</a></th>
<?php if (isset($_GET['modules']) || isset($_GET['themes'])): ?>
            <th><a href="/?sort=name<?=$resource; ?>">Name</a></th>
<?php endif; ?>
            <th><a href="/?sort=version<?=$resource; ?>">Version</a></th>
            <th><a href="/?sort=domain<?=$resource; ?>">Domain</a></th>
            <th><a href="/?sort=ip<?=$resource; ?>">IP</a></th>
            <th><a href="/?sort=os<?=$resource; ?>">OS</a></th>
            <th><a href="/?sort=server<?=$resource; ?>">Server</a></th>
            <th><a href="/?sort=php<?=$resource; ?>">PHP</a></th>
            <th><a href="/?sort=db<?=$resource; ?>">DB</a></th>
            <th><a href="/?sort=installed<?=$resource; ?>">Installed</a></th>
        </tr>
<?php foreach ($stats as $stat): ?>
        <tr>
            <td><?=$stat->id; ?></td>
<?php if (isset($_GET['modules']) || isset($_GET['themes'])): ?>
            <td><?=$stat->name; ?></td>
<?php endif; ?>
            <td><?=$stat->version; ?></td>
            <td><?=$stat->domain; ?></td>
            <td><?=$stat->ip; ?></td>
            <td><?=$stat->os; ?></td>
            <td><?=$stat->server; ?></td>
            <td><?=$stat->php; ?></td>
            <td><?=$stat->db; ?></td>
            <td><?=date('M j Y H:i:s', strtotime($stat->installed)); ?></td>
        </tr>
<?php endforeach; ?>
    </table>
    <a name="averages"></a>
    <a style="float: right;" href="#top">Top</a>
    <h1 class="header-top-border">Installation Averages:</h1>
    <table class="data-table width-50-10 left margin-10" cellpadding="0" cellspacing="0">
        <tr>
            <th colspan="4" class="text-center">PHP</th>
        </tr>
        <tr class="no-background">
            <th class="no-background border-right"><strong>5.4:</strong></th>
            <th class="no-background border-right"><strong>5.5:</strong></th>
            <th class="no-background border-right"><strong>5.6:</strong></th>
            <th class="no-background"><strong>Other:</strong></th>
        </tr>
        <tr class="no-background">
            <td class="no-background border-right"><?=$php['5.4']; ?>%</td>
            <td class="no-background border-right"><?=$php['5.5']; ?>%</td>
            <td class="no-background border-right"><?=$php['5.6']; ?>%</td>
            <td class="no-background"><?=$php['other']; ?>%</td>
        </tr>
    </table>
    <table class="data-table width-50 left" cellpadding="0" cellspacing="0">
        <tr>
            <th colspan="3" class="text-center">DB</th>
        </tr>
        <tr class="no-background">
            <th class="no-background border-right"><strong>MySQL</strong></th>
            <th class="no-background border-right"><strong>PgSQL</strong></th>
            <th class="no-background"><strong>SQLite</strong></th>
        </tr>
        <tr class="no-background">
            <td class="no-background border-right"><?=$db['mysql']; ?>%</td>
            <td class="no-background border-right"><?=$db['pgsql']; ?>%</td>
            <td class="no-background"><?=$db['sqlite']; ?>%</td>
        </tr>
    </table>
    <table class="data-table width-50-10 left margin-10" cellpadding="0" cellspacing="0">
        <tr>
            <th colspan="3" class="text-center">Server</th>
        </tr>
        <tr class="no-background">
            <th class="no-background border-right"><strong>Apache</strong></th>
            <th class="no-background border-right"><strong>IIS</strong></th>
            <th class="no-background"><strong>Other</strong></th>
        </tr>
        <tr class="no-background">
            <td class="no-background border-right"><?=$server['apache']; ?>%</td>
            <td class="no-background border-right"><?=$server['iis']; ?>%</td>
            <td class="no-background"><?=$server['other']; ?>%</td>
        </tr>
    </table>
    <table class="data-table width-50 left" cellpadding="0" cellspacing="0">
        <tr>
            <th colspan="4" class="text-center">OS</th>
        </tr>
        <tr class="no-background">
            <th class="no-background border-right"><strong>Linux</strong></th>
            <th class="no-background border-right"><strong>Unix</strong></th>
            <th class="no-background border-right"><strong>Windows</strong></th>
            <th class="no-background"><strong>Other</strong></th>
        </tr>
        <tr class="no-background">
            <td class="no-background border-right"><?=$os['linux']; ?>%</td>
            <td class="no-background border-right"><?=$os['unix']; ?>%</td>
            <td class="no-background border-right"><?=$os['windows']; ?>%</td>
            <td class="no-background"><?=$os['other']; ?>%</td>
        </tr>
    </table>
<?php else: ?>
    <p>There are currently no stats.</p>
<?php endif; ?>
<?php include __DIR__ . '/inc/footer.phtml'; ?>